name: Java MST CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin


      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build with Maven
        run: mvn -B clean compile


      - name: Run tests
        run: mvn test


      - name: Run MST algorithms
        run: |
          java -cp target/classes:target/dependency/* org.lattuse.algo.Main
        working-directory: ${{ github.workspace }}


      - name: Upload MST results
        uses: actions/upload-artifact@v4
        with:
          name: mst-results
          path: |
            datasets/output.json
            datasets/benchmark.csv

